#pragma once
#include "pluginterfaces/base/funknown.h"

namespace Steinberg{ namespace Vst{

	// processor GUID
	// {45F9FBE4-474F-41FB-834E-B08F2BE81278}
	// generated by http://www.guidgenerator.com
	static const FUID BLITSineHardSyncProcessorID(0x45F9FBE4, 0x474F41FB, 0x834EB08F, 0x2BE81278);

	// controller GUID
	// {F262E264-B172-4576-BF8D-1B316556B977}
	// (generated by http://www.guidgenerator.com)
	static const FUID BLITSineHardSyncControllerID(0xF262E264, 0xB1724576, 0xBF8D1B31, 0x6556B977);

}} // namespace
